version: "3.9"

services:
  prom-server:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prom-server
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /var/log:/var/log
