apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  mongo_uri: bW9uZ29kYjpleWVtb3d5c2FmdGdpbmdodThyJ1gzMjd2ZXZpbDhwbGRjNmlsbGJtZGVxMGRvYS1kdW5zZ3cyMQ== # base64 encoded value
  jwt_secret: MmM4ZWJzNjIyZDJhMjU3ZDU3ZDdhODU3ZTA5MGIzYTI3MmUyNjNiYjhmYjU1YWEyNGE1MjQ5MDc4ZTNjOTM= # base64 encoded value
  cloudinary_cloud_name: ZG1peWZlZGFx
  cloudinary_api_key: NjE4NjY3MTg3Njk0NzU5
  cloudinary_api_secret: QzAtaS1DaHhndjI2RjE4OGllbDJwN1g4dA== # base64 encoded value
  node_env: ZmFsc2U= # base64 encoded value
  mail_pass: YW11cWZudHJzaHl6eXBhYXg=
  mail_user: am91aW5kZXIua2FuZXJpa2FAZ21haWwuY29t
  mail_host: c210dHAuZ21haWwuY29t
  mail_secure: dHJ1ZQ== # base64 encoded value
  pg_user: cG9zdGdyZXM=
  pg_host: bG9jYWxob3N0
  pg_database: ZGV2bGluayA= # base64 encoded value
  pg_password: MTIzNA==
  pg_port: NTQzMg==
