apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  pg_user: cG9zdGdyZXM= # base64 encoded value for "postgres"
  pg_password: MTIzNA== # base64 encoded value for "1234"
